web:
    build: php
    ports:
        - "80:80"
    volumes:
        - /var/www:/var/www/html
        - /var/www/docker/php.ini:/usr/local/etc/php/conf.d/30-custom.ini
        - /var/www/docker/sites:/etc/apache2/sites-enabled
    environment:
        - ALLOW_OVERRIDE=true
    links:
        - db:db
        - maildev:maildev
        - elasticsearch:elasticsearch

db:
    image: mysql
    volumes:
        - /var/lib/boot2docker/mysql:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=root

maildev:
    image: djfarrelly/maildev
    ports:
        - "1080:80"

elasticsearch:
    image: elasticsearch:latest
